FROM ubuntu:18.04

ENV USER=unetuser

RUN apt-get update && \
    apt-get install -y sudo wget tar openssh-server

RUN useradd -m -s /bin/bash ${USER} && \
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER}

USER ${USER}
ENV HOME=/home/${USER}
WORKDIR ${HOME}

ENV PWD=pwd

# Setup environment
RUN echo ". ~/.bashrc" > .profile && \
    echo "COL=\"\\\\[\\\\033[0;33m\\\\]\"" > .bashrc && \
    echo "COL2=\"\\\\[\\\\033[1;31m\\\\]\"" >> .bashrc && \
    echo "NOCOL=\"\\\\[\\\\033[m\\\\]\"" >> .bashrc && \
    echo "export PS1=\"\${COL}\\\\u@\\\\h:\\\\w$ \${NOCOL}\"" >> .bashrc && \
    echo "export LD_LIBRARY_PATH=/home/unetuser/caffe_unet_package_18.04_cpu/lib:/home/unetuser/caffe_unet_package_18.04_cpu/extlib" >> .bashrc && \
    echo "export PATH=/home/unetuser/caffe_unet_package_18.04_cpu/bin:${PATH}" >> .bashrc && \
    wget https://lmb.informatik.uni-freiburg.de/lmbsoft/unet/caffe_unet_package_18.04_cpu.tar.gz && \
    tar xfz caffe_unet_package_18.04_cpu.tar.gz && \
    rm caffe_unet_package_18.04_cpu.tar.gz

ENTRYPOINT echo 'unetuser:${PWD}' | sudo chpasswd && sudo service ssh start && sudo rm /etc/sudoers.d/${USER} && /bin/bash
